# Generated by Django 3.0.3 on 2021-03-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_CV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='sessOb',
            field=models.CharField(max_length=15),
        ),
    ]
