# Generated by Django 3.0.3 on 2021-03-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_CV', '0004_auto_20210307_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exp', models.CharField(max_length=200)),
                ('date_debut', models.CharField(max_length=200)),
                ('date_fin', models.CharField(blank=True, max_length=200)),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('poste_occupe', models.CharField(max_length=200)),
                ('taches_effectuees', models.TextField()),
            ],
        ),
    ]
