# Generated by Django 3.0.3 on 2021-03-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_CV', '0005_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='total_exp',
            field=models.IntegerField(),
        ),
    ]
