# Generated by Django 3.0.3 on 2021-03-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_CV', '0006_auto_20210307_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_la_competence', models.CharField(max_length=200)),
                ('niveau_de_maitrise', models.CharField(max_length=5, null=True)),
                ('statut_competence', models.CharField(choices=[('A', 'Advance'), ('I', 'Intermediate'), ('D', 'Debutant')], max_length=200)),
            ],
        ),
    ]
