# Generated by Django 3.0.3 on 2021-03-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_CV', '0008_auto_20210308_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='statut_competence',
            field=models.CharField(blank=True, choices=[('A', 'Advance'), ('I', 'Intermediate'), ('D', 'Debutant')], max_length=200),
        ),
    ]
