# Generated by Django 3.0.3 on 2021-03-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_CV', '0010_competence_type_de_la_competence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='statut_competence',
            field=models.CharField(blank=True, choices=[('A', 'Advance'), ('I', 'Intermediate'), ('B', 'Beginner')], max_length=200),
        ),
    ]
