# Generated by Django 3.0.3 on 2021-03-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_CV', '0011_auto_20210308_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_projet', models.CharField(max_length=200)),
                ('language_utilise', models.CharField(choices=[('J', 'JAVA'), ('P', 'PYTHON'), ('PHP', 'PHP'), ('D', 'DJANGO'), ('R', 'REACT'), ('S', 'symfony')], max_length=200)),
            ],
        ),
    ]
