# Generated by Django 3.0.3 on 2021-03-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_CV', '0012_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
                ('titre', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
