# Generated by Django 3.0.3 on 2021-03-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_CV', '0013_autre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autre',
            name='titre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='language_utilise',
            field=models.CharField(choices=[('JAVA', 'JAVA'), ('PYTHON', 'PYTHON'), ('PHP', 'PHP'), ('DJANGO', 'DJANGO'), ('REACT', 'REACT'), ('SYMFONY', 'symfony')], max_length=200),
        ),
    ]
