# Generated by Django 3.0.3 on 2021-03-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_CV', '0015_auto_20210308_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.AddField(
            model_name='competence',
            name='nom_du_projet',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
