# Generated by Django 3.0.3 on 2021-03-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_CV', '0016_auto_20210308_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_contact', models.CharField(max_length=200)),
                ('prenom_contact', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('messagees', models.TextField()),
            ],
        ),
    ]
